(module
  (import "hdm:kernel/hardware-io" "shared-cluster-memory" (memory 100))
  (import "hdm:kernel/cell-dispatch" "invoke-cell" (func $invoke (param i32 i32 i32 i32) (result i32)))
  (func (export "run-tick") (param $cfg i32) (param $len i32) (result i32)
    (local $fnPtr i32) (local $fnLen i32) (local $st i32) (local $sw i32) (local $max i32)
    (local $steps i32) (local $bytes i32)
    (local.set $fnPtr (i32.load offset=0  (local.get $cfg)))
    (local.set $fnLen (i32.load offset=4  (local.get $cfg)))
    (local.set $st    (i32.load offset=8  (local.get $cfg)))
    (local.set $sw    (i32.load offset=12 (local.get $cfg)))
    (local.set $max   (i32.load offset=16 (local.get $cfg)))
    (local.set $bytes (i32.mul (local.get $sw) (i32.const 4)))
    (local.set $steps (i32.const 0))
    (block $done (loop $loop
      (br_if $done (i32.ge_u (local.get $steps) (local.get $max)))
      (local.set $steps (i32.add (local.get $steps) (i32.const 1)))
      (br_if $done (i32.eqz (call $invoke (local.get $fnPtr) (local.get $fnLen) (local.get $st) (local.get $bytes))))
      (br $loop)))
    (local.get $steps)))
