(module
  (import "hdm:kernel/hardware-io" "shared-cluster-memory" (memory 100))
  (import "hdm:kernel/cell-dispatch" "invoke-cell" (func $invoke (param i32 i32 i32 i32) (result i32)))
  (func (export "run-tick") (param $cfg i32) (param $len i32) (result i32)
    (local $stepP i32) (local $stepL i32) (local $st i32) (local $sb i32) (local $prP i32) (local $prL i32)
    (local $max i32) (local $count i32)
    (local.set $stepP (i32.load offset=0  (local.get $cfg)))
    (local.set $stepL (i32.load offset=4  (local.get $cfg)))
    (local.set $st    (i32.load offset=8  (local.get $cfg)))
    (local.set $sb    (i32.load offset=12 (local.get $cfg)))
    (local.set $prP   (i32.load offset=16 (local.get $cfg)))
    (local.set $prL   (i32.load offset=20 (local.get $cfg)))
    (local.set $max   (i32.load offset=24 (local.get $cfg)))
    (local.set $count (i32.const 0))
    (block $done (loop $loop
      (br_if $done (i32.ge_u (local.get $count) (local.get $max)))
      (br_if $done (i32.eqz (call $invoke (local.get $stepP) (local.get $stepL) (local.get $st) (local.get $sb))))
      (br_if $done (i32.eqz (call $invoke (local.get $prP) (local.get $prL) (local.get $st) (i32.const 4))))
      (local.set $count (i32.add (local.get $count) (i32.const 1)))
      (br $loop)))
    (local.get $count)))
