(module
  (import "hdm:kernel/hardware-io" "shared-cluster-memory" (memory 100))
  (import "hdm:kernel/cell-dispatch" "invoke-cell" (func $invoke (param i32 i32 i32 i32) (result i32)))
  (func (export "run-tick") (param $cfg i32) (param $len i32) (result i32)
    (local $stepP i32) (local $stepL i32) (local $st i32) (local $sb i32) (local $fnP i32) (local $fnL i32)
    (local $acc i32) (local $arg i32) (local $max i32) (local $i i32)
    (local.set $stepP (i32.load offset=0  (local.get $cfg)))
    (local.set $stepL (i32.load offset=4  (local.get $cfg)))
    (local.set $st    (i32.load offset=8  (local.get $cfg)))
    (local.set $sb    (i32.load offset=12 (local.get $cfg)))
    (local.set $fnP   (i32.load offset=16 (local.get $cfg)))
    (local.set $fnL   (i32.load offset=20 (local.get $cfg)))
    (local.set $acc   (i32.load offset=24 (local.get $cfg)))
    (local.set $arg   (i32.load offset=28 (local.get $cfg)))
    (local.set $max   (i32.load offset=32 (local.get $cfg)))
    (local.set $i (i32.const 0))
    (block $done (loop $loop
      (br_if $done (i32.ge_u (local.get $i) (local.get $max)))
      (br_if $done (i32.eqz (call $invoke (local.get $stepP) (local.get $stepL) (local.get $st) (local.get $sb))))
      (i32.store (local.get $arg) (local.get $acc))
      (i32.store (i32.add (local.get $arg) (i32.const 4)) (i32.load (local.get $st)))
      (local.set $acc (call $invoke (local.get $fnP) (local.get $fnL) (local.get $arg) (i32.const 8)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $loop)))
    (local.get $acc)))
